version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_4d3b7
      POSTGRES_PASSWORD: pwd_8f6a9c1
      POSTGRES_DB: school_mgmt_92f
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
