# Generated by Django 5.1.7 on 2025-05-13 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
                ('cycle', models.IntegerField()),
                ('periods', models.IntegerField()),
                ('prerequisites', models.ManyToManyField(related_name='required_for', to='ue.ue')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='section.section')),
            ],
        ),
    ]
