# Generated by Django 5.1.7 on 2025-04-16 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('section', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='UE',
            fields=[
                ('ueId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('credits', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ues', to='section.section')),
            ],
        ),
    ]
