# Generated by Django 5.1.7 on 2025-04-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ue', '0002_remove_ue_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='ue',
            name='prerequisites',
            field=models.ManyToManyField(related_name='required_for', to='ue.ue'),
        ),
    ]
