# Generated by Django 5.1.7 on 2025-03-29 19:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('employeeEmail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('studentEmail', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('employee_role', models.CharField(choices=[('Professeur', 'PROFESSOR'), ('Administrateur', 'ADMINISTRATOR'), ('Educateur', 'EDUCATOR')], default='Professeur', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Masculin', 'MALE'), ('Féminin', 'FEMALE')], default='Masculin', max_length=10)),
                ('identifier', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message="L'identifiant doit être composé de 6 chiffres et ne pas commencer par 0", regex='^[1-9][0-9]{5}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='security.account')),
                ('matricule', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Format matricule invalide', regex='^[12]\\d{8}$')])),
            ],
            bases=('security.account',),
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='security.account')),
                ('matricule', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Format matricule invalide', regex='^[12]\\d{8}$')])),
            ],
            bases=('security.account',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='security.account')),
            ],
            bases=('security.account',),
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.address'),
        ),
        migrations.AddField(
            model_name='account',
            name='contact_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.contactdetails'),
        ),
    ]
