# Generated by Django 5.1.7 on 2025-03-26 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('Masculin', 'MALE'), ('Féminin', 'FEMALE')], default='Masculin', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='security.account')),
                ('matricule', models.CharField(max_length=20)),
                ('is_administrator', models.BooleanField(default=False)),
            ],
            bases=('security.account',),
        ),
        migrations.RemoveField(
            model_name='account',
            name='contact_details_id',
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.address'),
        ),
        migrations.AddField(
            model_name='account',
            name='contact_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.contactdetails'),
        ),
        migrations.DeleteModel(
            name='Administrator',
        ),
    ]
