# Generated by Django 5.1.7 on 2025-03-29 20:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator',
            name='matricule',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Format matricule invalide', regex='^[12]\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='matricule',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Format matricule invalide', regex='^[12]\\d{8}$')]),
        ),
    ]
