# Generated by Django 5.1.7 on 2025-04-17 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ue', '0003_ue_prerequisites'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicUE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_ues', to='ue.ue')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_date', models.DateField()),
                ('academic_ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='ue_management.academicue')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('is_exempt', models.BooleanField(default=False)),
                ('academic_ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ue_management.academicue')),
            ],
        ),
    ]
