# Generated by Django 5.1.7 on 2025-04-27 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        ('ue', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicUE',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_ues', to='security.employee')),
                ('students', models.ManyToManyField(related_name='enrolled_ues', to='security.student')),
                ('ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_ues', to='ue.ue')),
            ],
            options={
                'unique_together': {('year', 'ue')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_date', models.DateField()),
                ('academic_ue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='ue_management.academicue')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Présent (présentiel)'), ('M', 'Présent (distanciel)'), ('A', 'Absent non justifié'), ('CM', 'Absent sous certificat'), ('D', 'Dispensé'), ('Abandon', 'Abandon')], default='A', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='security.student')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='ue_management.lesson')),
            ],
            options={
                'unique_together': {('lesson', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('period', models.IntegerField()),
                ('success', models.BooleanField(default=False)),
                ('isExempt', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('academicsUE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ue_management.academicue')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='security.student')),
            ],
            options={
                'unique_together': {('academicsUE', 'student')},
            },
        ),
    ]
