# Generated by Django 5.1.7 on 2025-05-06 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_remove_employee_role_account_role'),
        ('ue', '0001_initial'),
        ('ue_management', '0002_delete_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicue',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_ues', to='security.employee'),
        ),
        migrations.AlterField(
            model_name='academicue',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_ues', to='security.student'),
        ),
        migrations.AlterField(
            model_name='academicue',
            name='ue',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_ues', to='ue.ue'),
        ),
    ]
