# Generated by Django 5.1.7 on 2025-05-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ue_management', '0003_lesson_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('PROGRAMMED', 'Programmé'), ('COMPLETED', 'Terminé'), ('CANCELLED', 'Annulé'), ('REPORTED', 'Reporté')], default='PROGRAMMED', max_length=20),
        ),
    ]
