# Generated by Django 5.1.7 on 2025-05-10 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_remove_contactdetails_identifier_account_identifier'),
        ('ue_management', '0003_lesson_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicUeRegistration',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='security.student')),
                ('status', models.CharField(choices=[('AP', 'AP'), ('NP', 'NP')], default='AP', max_length=20)),
            ],
            bases=('security.student',),
        ),
    ]
