# Generated by Django 5.1.7 on 2025-05-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ue_management', '0001_initial'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicUeRegistration',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='security.student')),
                ('status', models.CharField(choices=[('AP', 'AP'), ('NP', 'NP')], default='AP', max_length=20)),
            ],
            bases=('security.student',),
        ),
    ] 