# Generated by Django 5.2 on 2025-05-12 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ue_management', '0004_alter_lesson_status'),
        ('ue_management', '0004_studentacademicueregistration'),
    ]

    operations = [
    ]
