# Generated by Django 5.1.7 on 2025-05-08 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sectionType', models.CharField(choices=[('MASTER', 'Master'), ('BACHELOR', 'Bachelier')], max_length=255)),
                ('sectionCategory', models.CharField(choices=[('ECONOMIC', 'Économique'), ('PARAMEDICAL', 'Paramédicale'), ('PEDAGOGICAL', 'Pédagogique'), ('SOCIAL', 'Sociale'), ('TECHNICAL', 'Technique'), ('AGRONOMIC', 'Agronomique'), ('ARTISTIC', 'Artistique')], max_length=255)),
                ('description', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
