# Generated by Django 5.1.7 on 2025-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='sectionCategory',
            field=models.CharField(choices=[('ECONOMIC', 'Économique'), ('PARAMEDICAL', 'Paramédicale'), ('PEDAGOGICAL', 'Pédagogique'), ('SOCIAL', 'Sociale'), ('TECHNICAL', 'Technique'), ('AGRONOMIC', 'Agronomique'), ('ARTISTIC', 'Artistique')], max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='sectionType',
            field=models.CharField(choices=[('MASTER', 'Master'), ('BACHELOR', 'Bachelier')], max_length=255),
        ),
    ]
