# Generated by Django 5.1.7 on 2025-05-13 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Présentiel', 'P'), ('Distanciel', 'M'), ('Certificat médical', 'CM'), ('Absence non justifiée', 'A'), ('Abandon', 'ABANDON'), ('Dispensé', 'D')], max_length=255)),
            ],
        ),
    ]
