# Generated by Django 5.1.7 on 2025-05-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
        ('ue_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Présentiel', 'P'), ('Distanciel', 'M'), ('Certificat médical', 'CM'), ('Absence non justifiée', 'A'), ('Abandon', 'ABANDON'), ('Dispensé', 'D')], max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_management.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.student')),
            ],
        ),
    ]
