# Generated by Django 5.1.7 on 2025-05-06 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0003_remove_employee_role_account_role'),
        ('ue_management', '0002_delete_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'PRESENT'), ('M', 'PRESENT_DISTANCIEL'), ('A', 'ABSENT_NON_JUSTIFIE'), ('CM', 'ABSENT_SOUS_CERTIFICAT'), ('D', 'DISPENSE'), ('Abandon', 'ABANDON')], max_length=255)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ue_management.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.student')),
            ],
        ),
    ]
