# Generated by Django 5.1.7 on 2025-05-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'PRESENT'), ('M', 'PRESENT_DISTANCIEL'), ('A', 'ABSENT_NON_JUSTIFIE'), ('CM', 'ABSENT_SOUS_CERTIFICAT'), ('D', 'DISPENSE'), ('Abandon', 'ABANDON')], max_length=255)),
            ],
        ),
    ]
