# Generated by Django 5.1.7 on 2025-05-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Présentiel', 'P'), ('Distanciel', 'M'), ('Certificat médical', 'CM'), ('Absence non justifiée', 'A'), ('Abandon', 'ABANDON'), ('Dispensé', 'D')], max_length=255),
        ),
    ]
