# Generated by Django 5.1.7 on 2025-05-13 18:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message="L'identifiant doit être composé de 6 chiffres et ne pas commencer par 0", regex='^[1-9][0-9]{5}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('ADMINISTRATOR', 'Administrateur'), ('STUDENT', 'Etudiant'), ('PROFESSOR', 'Enseignant'), ('EDUCATOR', 'Educateur')], default='STUDENT', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zipCode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=10)),
                ('complement', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(choices=[('Masculin', 'MALE'), ('Féminin', 'FEMALE')], default='Masculin', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='security.account')),
                ('matricule', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Format matricule invalide', regex='^[12]\\d{8}$')])),
            ],
            bases=('security.account',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='security.account')),
            ],
            bases=('security.account',),
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.address'),
        ),
        migrations.AddField(
            model_name='account',
            name='contactDetails',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='security.contactdetails'),
        ),
    ]
