# Generated by Django 5.1.7 on 2025-05-10 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdetails',
            name='identifier',
        ),
        migrations.AddField(
            model_name='account',
            name='identifier',
            field=models.CharField(default='100001', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message="L'identifiant doit être composé de 6 chiffres et ne pas commencer par 0", regex='^[1-9][0-9]{5}$')]),
            preserve_default=False,
        ),
    ]
