# Generated by Django 5.1.7 on 2025-04-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Professeur', 'PROFESSOR'), ('Administrateur', 'ADMINISTRATOR'), ('Educateur', 'EDUCATOR')], default='Professeur', max_length=20),
        ),
    ]
