# Generated by Django 5.1.7 on 2025-04-26 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_alter_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('Professeur', 'PROFESSOR'), ('Administrateur', 'ADMINISTRATOR'), ('Educateur', 'EDUCATOR'), ('Etudiant', 'STUDENT')], default='Etudiant', max_length=20),
        ),
    ]
