# Generated by Django 5.1.7 on 2025-04-05 17:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_alter_educator_matricule_alter_instructor_matricule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='security.account')),
                ('matricule', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Format matricule invalide', regex='^[12]\\d{8}$')])),
            ],
            bases=('security.account',),
        ),
        migrations.AddField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
