# Generated by Django 5.1.7 on 2025-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_administrator_address_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='Liège', max_length=50),
            preserve_default=False,
        ),
    ]
