# Generated by Django 5.1.7 on 2025-04-05 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_address_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='employeeEmail',
            new_name='employee_email',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='studentEmail',
            new_name='student_email',
        ),
    ]
